import "./globals.css";
import Header from "/components/Header";
import Footer from "/components/Footer";

import { Toaster } from "/components/ui/toaster";

import { ThemeProvider } from "/components/ThemeProvider";

import { Sen } from "next/font/google";

const SentFont = Sen({
  subsets : ['latin'],
  weight: ["400", "500","600","700"],
  display: "swap"
})

//import components 




export const metadata = {
  title: "Photography",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={SentFont.className}>
        <ThemeProvider attribute="class" defaultTheme='light'>
          <Header />
          {children}
          <Footer />
          <Toaster />
        </ThemeProvider>
        

      </body>
    </html>
  );
}
